name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  update-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update snake animation
        run: curl -sSL https://raw.githubusercontent.com/NunoAndrezo/NunoAndrezo/output/snake.svg -o snake.svg